#                                                          #
# Default subroutes configuration for the IdNeosIo package #
#                                                          #


-
  name: 'Homepage'
  uriPattern: ''
  defaults:
    '@package':    'Neos.IdNeosIo'
    '@controller': 'Welcome'
    '@action':     'welcome'
    '@format':     'html'

-
  name: 'Login Actions'
  uriPattern: 'login(/{@action})'
  defaults:
    '@package':    'Neos.IdNeosIo'
    '@controller': 'Login'
    '@action':     'login'
    '@format':     'html'

-
  name: 'Activate account'
  uriPattern: 'user/activate/{token}'
  defaults:
    '@package':    'Neos.IdNeosIo'
    '@controller': 'User'
    '@action':     'create'
    '@format':     'html'
    'token':       ''

-
  name: 'Reset password link'
  uriPattern: 'user/onetimelogin/{token}'
  defaults:
    '@package':    'Neos.IdNeosIo'
    '@controller': 'ResetPassword'
    '@action':     'onetimeLogin'
    '@format':     'html'
    'token':       ''

-
  name: 'Reset Password Actions'
  uriPattern: 'resetpassword(/{@action})'
  defaults:
    '@package':    'Neos.IdNeosIo'
    '@controller': 'ResetPassword'
    '@action':     'index'
    '@format':     'html'

-
  name: 'User Profile Actions'
  uriPattern: 'user(/{@action})'
  defaults:
    '@package':    'Neos.IdNeosIo'
    '@controller': 'User'
    '@action':     'index'
    '@format':     'html'