#                                                                        #
# Default subroutes configuration for the NeosDiscouresSso package       #
#                                                                        #

##
# Default route to the Discourse SSO Controller

-
  name: 'Default Login Action'
  uriPattern: 'discourse/authenticatediscourseuser'
  defaults:
    '@package':    'Neos.DiscourseCrowdSso'
    '@controller': 'DiscourseCrowdSso'
    '@action':     'authenticateDiscourseUser'
    '@format':     'html'
  appendExceedingArguments: true
